modified:   src/sass/components/_header.scss
AleksandraAleksinska/Projekt-Filmoteka pull request #22
Opened 2023-04-18 16:02 UTC by DamianDawidowski

2023-04-19 09:56 UTC, AleksandraAleksinska requested changes

2023-04-19 09:56 UTC, AleksandraAleksinska commented on src/sass/components/_header.scss
>    background-repeat: no-repeat;
Tu musimy dodać jeszcze width: 100%, żeby nam się tło nagłówka płynnie zmieniało przy każdej rozdzielczości :)

2023-04-19 09:56 UTC, AleksandraAleksinska commented on src/sass/components/_header.scss
> +    &__input {
Zmienia się też szerokość &__form - trzeba będzie dopasować do każdej rozdzielczości :)

2023-04-19 09:56 UTC, AleksandraAleksinska commented on src/sass/components/_header.scss
> +    padding: 40px 0px 92px;
do weryfikacji padding 92px - na podglądzie nakłada się na niższe sekcje, a chyba nic nie zmienia, warto sprawdzić :)

2023-04-20 17:00 UTC, DamianDawidowski commented on src/sass/components/_header.scss
> +    &__input {
dodane w __input-area 
dla min-width: 768px
width: 336px; 
dla min-width: 1280px
 width: 394px;

2023-04-20 18:01 UTC, AleksandraAleksinska approved these changes

2023-04-21 11:05 UTC, AleksandraAleksinska approved these changes

2023-04-21 11:05 UTC, AleksandraAleksinska commented on src/sass/components/_header.scss
trzeba dodać margin-top do klasy .header__libBtn-area {
    justify-content: center;
    align-items: center;
    display: flex;
    margin-top: 63px dla mobile (dla tablet i desktop 49px;

2023-04-21 11:07 UTC, merged